### PR TITLE
Grahpql: Add stopCoordinates to Segment type

### PR DESCRIPTION
**Pull request by tbergq**
When drawing lines on the map we need to pass an array of
gps coordinates to the draw-line component. This field will make
the drawing of the map a lot easier than if we have to fetch
the coordinates from departure?.stop?.coordinates?.lat and
arrival?.stop?.coordinates?.lat

### CODE REVIEW

**Comment by michalsanger** [comment]
This is interesting topic. Computed fields vs just querying the fields from graph. Does it really bring that much benefits here? `Sector` has `departure` and `arrival` looks simple to me to go deep into the graph and grab the data from related location. But as you work with this on FE, where do you see the added value?

**Comment by tbergq** [comment]
Without this, my component would look like this

```
// @flow

import * as React from 'react';
import { MapView } from '@kiwicom/margarita-map';
import { StyleSheet, Text } from '@kiwicom/universal-components';
import { graphql, createFragmentContainer } from '@kiwicom/margarita-relay';
import { getCenter } from 'geolib';
import memoize from 'memoize-one';

import type { MapLines as SegmentType } from './__generated__/MapLines.graphql';

type Props = {|
  +data: ?SegmentType,
|};

const MapLines = (props: Props) => {
  const outbound = props.data?.outbound?.segments ?? [];
  const inbound = props.data?.inbound?.segments ?? [];
  const segments = [...outbound, ...inbound];
  return segments.map((segment, index) => (
    <MapView.Polyline
      key={index}
      coordinates={[
        {
          latitude: segment?.departure?.stop?.coordinates?.lat,
          longitude: segment?.departure?.stop?.coordinates?.lng,
        },
        {
          latitude: segment?.arrival?.stop?.coordinates?.lat,
          longitude: segment?.arrival?.stop?.coordinates?.lng,
        },
      ]}
      strokeColor={index < outbound.length ? 'deeppink' : 'cyan'}
      strokeWidth={2}
    />
  ));
};
export default createFragmentContainer(
  MapLines,
  graphql`
    fragment MapLines on BookingInterface {
      ... on BookingReturn {
        outbound {
          segments {
            departure {
              stop {
                coordinates {
                  lat
                  lng
                }
              }
            }
            arrival {
              stop {
                coordinates {
                  lat
                  lng
                }
              }
            }
          }
        }

        inbound {
          segments {
            departure {
              stop {
                coordinates {
                  lat
                  lng
                }
              }
            }
            arrival {
              stop {
                coordinates {
                  lat
                  lng
                }
              }
            }
          }
        }
      }
    }
  `,
);
```

With this structure, I can do this: 

```
const DrawSegmentLine = (props: Props) => {
  const coordinates = props.data?.stopCoordinates;
  if (coordinates == null) {
    return null;
  }

  return (
    <MapView.Polyline
      coordinates={coordinates}
      strokeColor={props.color}
      strokeWidth={1}
    />
  );
};

export default createFragmentContainer(
  DrawSegmentLine,
  graphql`
    fragment DrawSegmentLine on Segment {
      stopCoordinates {
        lat
        lng
      }
    }
  `,
);
```

**Comment by michalsanger** [comment]
So you mean the first version has too big query? How about add those repetitive props into fragment?
```graphql
fragment StopCoordinates on RouteStop {
  stop {
    coordinates {
      lat
      lng
    }
  }
}
```

**Comment by tbergq** [comment]
So you suggest something like this: 

```
// @flow

import * as React from 'react';
import { MapView } from '@kiwicom/margarita-map';
import { graphql, createFragmentContainer } from '@kiwicom/margarita-relay';

import type { DrawSegmentLine as SegmentType } from './__generated__/DrawSegmentLine.graphql';

type Props = {|
  +data: ?SegmentType,
  +color: string,
|};

const DrawSegmentLine = (props: Props) => {
  return (
    <MapView.Polyline
      coordinates={[
        { ...props.data?.departure?.stop?.coordinates },
        { ...props.data?.arrival?.stop?.coordinates },
      ]}
      strokeColor={props.color}
      strokeWidth={1.5}
    />
  );
};

export default createFragmentContainer(
  DrawSegmentLine,
  graphql`
    fragment DrawSegmentLineStopCoordinates on RouteStop {
      stop {
        coordinates {
          latitude: lat
          longitude: lng
        }
      }
    }
    fragment DrawSegmentLine on Segment {
      departure {
        ...DrawSegmentLineStopCoordinates @relay(mask: false)
      }
      arrival {
        ...DrawSegmentLineStopCoordinates @relay(mask: false)
      }
    }
  `,
);
```

**Comment by tbergq** [comment]
Yeah, that seems to work for me, so I will close this PR then.

**Pull request closed without merging**
