### PR TITLE
Chore: Improved file structure in packages/components/src

### PR DESCRIPTION
**Pull request by RobinCsl**
Summary: This is to be more consistent with @kiwicom/universal-components

### CODE REVIEW

**Comment by RobinCsl** [comment]
Well, this was just to be more consistent with universal-components and @JoseDuSV mentioned that in a previous CR. 
@FilipMessa: what's your opinion?

**Comment by tbergq** [comment]
I find it hard to find the correct files 🙈 
screenshot 2019-01-07 at 11 38 01

**Comment by RobinCsl** [comment]
But if you look for something specific like `Button`, then you get the correct files, don't you?
In my opinion, `index.js` is so generic that it might not be the best search keyword anyway.

**Comment by FilipMessa** [comment]
I understand your motivation but I also don't see the value of what `index.js` files brings when is used only for export the components.
Is there some added value, if we will do it this way with `index.js`?

**Comment by JoseDuSV** [comment]
Personally I don't have a strong opinion about this as with `universal-components`.
I prefer current state without extra `index.js`.

But it will be reasonable to have it unified if we expect more components shuffling between repos in the future. On the other hand, now it's much clearer which component belongs to which project, so it probably won't happen that often.

**Comment by RobinCsl** [comment]
I will close this PR and use the different convention of file structure that you guys prefer, and open a new PR for it.

**Comment by FilipMessa** [comment]
Thanks 

> I will close this PR and use the different convention of file structure that you guys prefer, and open a new PR for it.

**Pull request closed without merging**
