### PR TITLE
Use @kiwicom/relay package

### PR DESCRIPTION
**Pull request by tbergq**

### CODE REVIEW

**Comment by tbergq** [comment]
When actually using the createFragmentContainer from `@kiwicom/relay` package, there are a lot of flow errors. 

I need your help on this @mrtnzlml

**Comment by tbergq** [comment]
Seems flow types are not ready yet. We will come back to this later.

**Comment by mrtnzlml** [comment]
Please revert the `flow-typed` definitions (only that) so you will survive this period... :)

**Comment by tbergq** [comment]
It does not work good with exports from `@kiwicom/relay`, I probably need to revert that as well

**Comment by mrtnzlml** [comment]
Be creative :)

```
[untyped]
.*/node_modules/@kiwicom/relay/
```

Your team has to learn how to do incremental changes, not a big chunks of work.

**Pull request closed without merging**
