### PR TITLE
Delete yarn.lock, yarn install

### PR DESCRIPTION
**Pull request by tbergq**
See if this can fix our problems with CI failing

Please checkout this branch, do yarn and see if you get any diff 😊

### CODE REVIEW

**Comment by FilipMessa** [comment]
I have these:
screen shot 2019-01-29 at 16 05 11

**Comment by FilipMessa** [comment]
But it is almost same but it removed this `git+` prefix

**Comment by tbergq** [comment]
@FilipMessa I have

```
Tronds-MacBook-Pro-2:margarita trondbergquist$ node -v
v11.6.0
Tronds-MacBook-Pro-2:margarita trondbergquist$ yarn -v
1.13.0
```

what versions do you have?

**Comment by FilipMessa** [comment]
I tried your setup but same results:
```
fmessa at holoch in ~/repos/margarita on try-to-fix-ci [!]
$ yarn -v && node -v
1.13.0
v11.6.0
```

**Comment by JoseDuSV** [comment]
@tbergq I'm having same problem on
```
node -v && yarn -v
v10.15.0
1.13.0
```

**Comment by JoseDuSV** [comment]
Interesting is that if I delete `yarn.lock` file and run `yarn install` to create a new one, there is no difference and it looks exactly like one in this PR with all the `git+` prefixes. 🤔

**Comment by tbergq** [comment]
So maybe everyone needs to delete their `yarn.lock` and run `yarn install`

**Comment by FilipMessa** [comment]
I removed `yarn.lock` and then run `yarn install` but now there are few new dependencies versions.
 
screen shot 2019-01-30 at 10 56 02

**Pull request closed without merging**
