### PR TITLE
FIX: fix yarn lock

### PR DESCRIPTION
**Pull request by FilipMessa**
This MR fix CI error:

`error https://registry.yarnpkg.com/rxjs/-/rxjs-6.3.3.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, chmod '/home/circleci/.cache/yarn/v4/npm-rxjs-6.3.3-3c6a7fa420e844a81390fb1158a9ec614f4bad55/node_modules/rxjs/scheduler/queue.js.map'"`

### CODE REVIEW

**Comment by tbergq** [comment]
Any reason why the `yarn.lock` is changing? Could it be from different node-versions? If so, maybe we should set engine in package.json?

**Comment by FilipMessa** [comment]
@tbergq 

I found this as a solution here 
https://github.com/yarnpkg/yarn/issues/6312#

**Comment by tbergq** [comment]
Yes, but checking out this branch and doing `yarn install` with node 11 undo the change in yarn.lock

**Comment by FilipMessa** [comment]
Hm 🤔 I will try, but Yes definitely we shoul add an engine into the `package.json`

**Comment by tbergq** [comment]
Happens also on node 10.13 for me, so maybe it is related to yarn version?

**Comment by FilipMessa** [comment]
so something like this?

```
"engines": {
    "node": ">=11.0.0",
    "yarn": ">=1.13.0"
}
```

**Comment by tbergq** [comment]
The CI runs on node 10, so then the config should be upgraded as well.

**Comment by tbergq** [comment]
And even with node `11.6.0` and yarn `1.13.0` My lock file changes when doing yarn on this branch

**Comment by tbergq** [comment]
Hmm, well, my machine adds some more changes to yarn.lock, I will try commit them on top of this, then see what happens

**Comment by tbergq** [comment]
🙈 my machine does not want me to work on margarita

**Comment by tbergq** [comment]
Removing my commit again since problem seems to be on my machine

**Comment by FilipMessa** [comment]
> 🙈 my machine does not want me to work on margarita
Your computer doesn't believe in the RNW? 💔

**Comment by tbergq** [comment]
Seems @RobinCsl also get's another `yarn.lock` so it is not just me, right @RobinCsl ?

**Comment by JoseDuSV** [comment]
Same here, differences:
screenshot 2019-01-29 at 14 28 41

**Comment by tbergq** [comment]
how about #170 in favor of this one?

**Comment by FilipMessa** [comment]
I close this because it should be solved by #170

**Comment by tbergq** [comment]
>I close this because it should be solved by #170

it was not 🙁

**Pull request closed without merging**
